CREATE DATABASE IF NOT EXISTS RSVPs;

USE RSVPs;

CREATE TABLE IF NOT EXISTS RSVPs (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    KnownAllergies TEXT,
    NumberOfGuests INT DEFAULT 1
);
